name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        env:
          REACT_APP_STORE_SHEET_KEY: ${{ secrets.REACT_APP_STORE_SHEET_KEY }}
          REACT_APP_STORE_SHEET_ID: ${{ secrets.REACT_APP_STORE_SHEET_ID }}

      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
